[package]
name = "rust-napi-examples"
version = "0.1.0"
authors = ["Jolyon Saunders <jol.saund@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
